# Generated by Django 5.2.17 on 2026-09-16 04:34

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TrainingJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("image", models.CharField(max_length=512)),
                ("command", models.JSONField(blank=True, default=list)),
                ("requested_gpu", models.CharField(default="0", max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("cancel_requested_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="ContainerExecution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "container_id",
                    models.CharField(blank=True, max_length=64, null=True, unique=True),
                ),
                ("image_digest", models.CharField(blank=True, max_length=255)),
                ("assigned_gpu", models.CharField(blank=True, max_length=128)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("starting", "Starting"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="starting",
                        max_length=16,
                    ),
                ),
                ("output_path", models.TextField(blank=True)),
                ("exit_code", models.IntegerField(blank=True, null=True)),
                ("error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "training_job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="executions",
                        to="backend.trainingjob",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
            },
        ),
    ]
