# Generated by Django 5.2.17 on 2026-09-22 14:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0002_project_snapshots"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainingjob",
            name="dockerfile",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="trainingjob",
            name="dockerfile_source",
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
