# Generated by Django 5.2.17 on 2026-09-22 15:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0003_training_dockerfiles"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainingjob",
            name="environment_validation",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
