# Generated by Django 5.2.17 on 2026-09-22 16:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0005_trainingjob_finished_at_trainingjob_status_dataset_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="containerexecution",
            name="build_attempts",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="containerexecution",
            name="build_finished_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="containerexecution",
            name="build_log",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="containerexecution",
            name="build_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="containerexecution",
            name="build_token",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trainingjob",
            name="error",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="containerexecution",
            name="state",
            field=models.CharField(
                choices=[
                    ("building", "Building image"),
                    ("starting", "Starting"),
                    ("running", "Running"),
                    ("succeeded", "Succeeded"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                ],
                default="starting",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="trainingjob",
            name="status",
            field=models.CharField(
                choices=[
                    ("queued", "Queued"),
                    ("building", "Building image"),
                    ("running", "Running"),
                    ("finished", "Finished"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                ],
                default="queued",
                db_index=True,
                max_length=16,
            ),
        ),
        migrations.AddConstraint(
            model_name="containerexecution",
            constraint=models.UniqueConstraint(
                condition=models.Q(("state__in", ["building", "starting", "running"])),
                fields=("training_job",),
                name="one_active_execution_per_job",
            ),
        ),
        migrations.AddConstraint(
            model_name="containerexecution",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("state__in", ["building", "starting", "running"]),
                    models.Q(("assigned_gpu", ""), _negated=True),
                ),
                fields=("assigned_gpu",),
                name="one_active_execution_per_gpu",
            ),
        ),
    ]
